Group assignment
Tom-Goring/EnterpriseSystemsDevelopment pull request #5
Opened 2020-11-30 21:19 UTC by Maxwell2Gyamfi

Implemented appointment creation:
1. User initially selects available doctors, date and appointment length on first page. 
2. User clicks "available slots button which generates available slots from 9:00 to 18:00 based on appointment length and calendar
3. The system generate slots based on doctor availability of the selected day
4. The system requests customer name, appointment type, and appointment starting time and ending end
5. User clicks on confirm appointment to confirm appointment with doctor
6. Final page displays appointment confirmed with a button to return to Homepage

Extras
1. Could ask for more details such as customer email, home address etc. To be discusses during scrum
2. Could create function to display all appointments based on selected doctor, date and time.

2020-11-30 23:07 UTC, Tom-Goring requested changes
Reading through the actual logic it looks pretty sound - pretty good work here (and quick too 🥇), will just need a bit of cleanup and refactoring before a merge. I would start by rebasing onto master and moving and renaming files into better places. It would be great if you could refactor to use a `role` column on the Users table for finding doctors and nurses, then I could test it locally to have a better poke around. Otherwise looks pretty 👍

2020-11-30 23:07 UTC, Tom-Goring commented on src/main/java/Controllers/NewServlet.java
> +        doctorsList = app.getDoctors();
This can probably be replaced with a DAO method that fetches all Users with the doctor role from the database?

2020-12-01 10:30 UTC, CharlievWilliams commented on src/main/java/Controllers/AppointmentDetails.java
> +import java.io.PrintWriter;
In Intellij IDEA I like to use `CTRL + ALT + L` and `CTRL + ALT + O` to automatically reformat code and optimize imports. I tend to just spam that on any page I touch.

2020-12-01 10:39 UTC, CharlievWilliams commented on src/main/java/Utils/Appointment.java
> +        boolean addSlot = false;
`addSlot` does not need to be given a value here because it will always be set on line `194`

2020-12-01 10:46 UTC, CharlievWilliams commented on src/main/java/Utils/Appointment.java
> +    public boolean compareSelectedTime(String[] time, ArrayList<Event> currEvents) {
No change needed here but - When I see a boolean function personally I prefer to see a name like `IsAvailableSlot` or something like that. (I'm not exactly sure what the function does so you'd be able to give it a better name.)

That way when it is called in an if statement it is immediately clear what it is doing.
`addSlot = IsAvailableSlot(hours, currEvents);`

2020-12-01 10:53 UTC, CharlievWilliams commented
I agree with Tom, this is really good work, mate!

I don't want to spam the PR with syntax comments because you already have enough to look at. I'm not sure what IDE you're using but much of my suggestions would get called out by Intellij IDEA in the IDE.

The ones I'm consistently seeing are things like:
Variable initializer is redundant
New function can be replaced with Lambda
Lowercase should be replaced with CamelCase

Just simple things like that. In IDEA you can select the code and then `ALT + ENTER` to automatically perform the suggestion from the IDE.

2020-12-01 11:00 UTC, CharlievWilliams commented
Also, I'm not sure if you've dealt with merge conflicts before?

Regardless- the way I'd deal with it is:

1. Open local master branch and pull updates from origin
2. Open your feature branch and merge your updated master branch into it
3. You will then be asked to resolve the merge conflicts by keeping the most relevant things from each branch. You should test the software still works after this. If it does not, it can always be reverted and you can do it again. The beauty of version control.

Personally I interact with Version Control by using the GUI in the bottom right of Intellij IDEA.

2020-12-08 12:53 UTC, CharlievWilliams commented
In the future, it may prove useful to split up the work as you go into a number of smaller PR's. That would keep the changes to a more manageable level, and I know Tom and I will be able to look at them quickly if they need review.

That's something that helped me in the past. Up to you though mate!

2020-12-12 20:44 UTC, closed without merging